---
- name: "Add settings per ubuntu release"
  include_vars: "{{ ansible_distribution_release }}.yml"

- name: Update apt-cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install packages.
  action: apt pkg="{{ item }}" state=present
  with_items: "{{ base_apt_packages_default }}"

- name: Make sure /dev/xconsole is there for rsyslog
  shell: mknod -m 640 /dev/xconsole p && chown root:adm /dev/xconsole || echo /dev/xconsole already exists.
  when: ansible_distribution_release == 'trusty'

- name: Install extra packages.
  action: apt pkg="{{ item }}" state=present
  with_items: "{{ base_apt_packages_extra }}"

- name: Ansible motd
  action: template src=etc-update-motd-d-95-ansible.j2 dest=/etc/update-motd.d/95-ansible mode=755

- name: Enable unattended-upgrades.
  template: src=apt-20auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
  when: base_is_server

- name: Install server packages.
  action: apt pkg="{{ item }}" state=present
  with_items:
    - unattended-upgrades
  when: base_is_server

- name: Set timezone variables
  copy: >
    content="{{ base_timezone }}\n"
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - Update timezone

- name: Modify (Increase) soft nproc
  when: base_is_server
  pam_limits:
    domain: drunomics
    limit_type: soft
    limit_item: nproc
    value: "{{ base_max_openfiles }}"

    
- name: Modify (Increase) hard nproc
  when: base_is_server
  pam_limits:
    domain: drunomics
    limit_type: hard
    limit_item: nproc
    value: "{{ base_max_openfiles }}"
    
- name: Modify (Increase) soft nofile
  when: base_is_server
  pam_limits:
    domain: drunomics
    limit_type: soft
    limit_item: nofile
    value: "{{ base_max_openfiles }}"
    
- name: Modify (Increase) hard nofile
  when: base_is_server
  pam_limits:
    domain: drunomics
    limit_type: hard
    limit_item: nofile
    value: "{{ base_max_openfiles }}"

- name: Modify (Increase) soft nproc root
  when: base_is_server
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: nproc
    value: "{{ base_max_openfiles }}"
    
- name: Modify (Increase) hard nproc root
  when: base_is_server
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: nproc
    value: "{{ base_max_openfiles }}"
    
- name: Modify (Increase) soft nofile root
  when: base_is_server
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: nofile
    value: "{{ base_max_openfiles }}"
    
- name: Modify (Increase) hard nofile root
  when: base_is_server
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: nofile
    value: "{{ base_max_openfiles }}"
