---
- name: "Add settings per ubuntu release"
  include_vars: "{{ ansible_distribution_release }}.yml"

- name: Install packages.
  action: apt pkg="{{ item }}" state=present
  with_items: "{{ base_apt_packages_default }}"

- name: Make sure /dev/xconsole is there for rsyslog
  shell: mknod -m 640 /dev/xconsole p && chown root:adm /dev/xconsole || echo /dev/xconsole already exists.
  when: ansible_distribution_release == 'trusty'

- name: Install extra packages.
  action: apt pkg="{{ item }}" state=present
  with_items: "{{ base_apt_packages_extra }}"

- name: Ansible motd
  action: template src=etc-update-motd-d-95-ansible.j2 dest=/etc/update-motd.d/95-ansible mode=755

- name: Enable unattended-upgrades.
  template: src=apt-20auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
  when: base_is_server

- name: Install server packages.
  action: apt pkg="{{ item }}" state=present
  with_items:
    - unattended-upgrades
  when: base_is_server

- name: Set timezone variables
  copy: >
    content="{{ base_timezone }}"
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - Update timezone
