---
- name: Install packages.
  action: apt pkg="{{ item }}" state=present
  with_items:
    - rsyslog
    - vim
    - unzip
    - curl
    - python-software-properties
    - htop

- name: Install extra packages.
  action: apt pkg="{{ item }}" state=present
  with_items: base_apt_packages_extra

- name: Ansible motd
  action: template src=etc-update-motd-d-95-ansible.j2 dest=/etc/update-motd.d/95-ansible mode=755

- name: Enable unattended-upgrades.
  template: src=apt-20auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
  when: base_is_server

- name: Install server packages.
  action: apt pkg="{{ item }}" state=present
  with_items:
    - unattended-upgrades
  when: base_is_server

# Fix for rsyslogd not running at container start.
- name: Copy custom rsyslogd start script
  copy: src=drunomics_rsyslog dest=/etc/init.d/drunomics_rsyslog owner=root group=root mode=0554

- name: Start rsyslog via rc.local
  lineinfile: dest=/etc/rc.local line="/etc/init.d/drunomics_rsyslog" state=present
